<?php

return [
    /**
     * Authentication - Configuration
     */
    'token_params' => NULL,
    'consumer_key' => env('PESAPAL_CONSUMER_KEY','YOUR CONSUMER'),
    'consumer_secret' => env('PESAPAL_CONSUMER_SECRET','YOUR    CONSUMER SECRET'),
    'live_iframelink' => 'https://www.pesapal.com/API/PostPesapalDirectOrderV4',
    'demo_iframelink' => 'http://demo.pesapal.com/api/PostPesapalDirectOrderV4',

    /**
     * Define the callback_url
     * This is the full url pointing to the page the iframe redirects 
     *  to after processing the order on pesapal.com
    */
    'callback_url' => env('PESAPAL_CALLBACK_URL', 'http://test.com/payment-gateways-php/pesapal-php/'),

    /**
     * Field Names
     * You may wish for to select prefered form details posted by your 
     * App to be used by pesapal.
     * You can add more `Fields` here if you wish.
     * NOTE: default value = MERCHANT
     * */
 
   'fields' => [
 
       'amount' => 'number_format(PESAPAL_FIELD_AMOUNT, 2)', //format amount to 2 decimal places
       'description' => 'PESAPAL_FIELD_DESC',
       'type' => 'MERCHANT', //default value = MERCHANT
       'reference' => 'PESAPAL_FIELD_REF', //unique order id of the transaction, generated by merchant
       'first_name' => 'PESAPAL_FIELD_FNAME',
       'last_name' => 'PESAPAL_FIELD_LNAME',
       'email' => 'PESAPAL_FIELD_EMAIL',
       'phonenumber' => 'PESAPAL_FIELD_PHONE' //ONE of email or     phonenumber is required
 
   ]
];